load('C:\Users\Usuario\Documents\GitHub\ViconMatlab\KT\DataMatlab\S03.mat')
m_target = SerratoPreFrontal;
m_rms = sqrt(movmean(SerratoPreFrontal.^2, 1000));
m_mvc = max(serratoMVCRMS);
m_norm = (m_rms/m_mvc)*100;

createfigure(m_target, m_rms, m_norm)
function createfigure(Y1, Y2, Y3)

%CREATEFIGURE(Y1, Y2, Y3)
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data
%  Y3:  vector of plot y data

%  Auto-generated by MATLAB on 21-Jul-2023 11:34:52

% Create figure
f = figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(3,1,1);
hold(subplot1,'on');

% Create plot
plot(Y1,'LineWidth',1,'Color',[0 0 0]);

% Create ylabel
ylabel({'Amplitude (V)'});

% Create xlabel
xlabel({'Time (s)'});

% Create title
title({'sEMG - Raw Signal'});

box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'XTickLabel',{'0','25','50','75','100','125'});
% Create subplot
subplot2 = subplot(3,1,2);
hold(subplot2,'on');

% Create plot
plot(Y2,'LineWidth',1,'Color',[0 0 0]);

% Create ylabel
ylabel({'Amplitude (V)'});

% Create xlabel
xlabel({'Time (s)'});

% Create title
title({'sEMG - Root Mean Squared'});

box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'XTickLabel',{'0','25','50','75','100','125'});
% Create subplot
subplot3 = subplot(3,1,3);
hold(subplot3,'on');

% Create plot
plot(Y3,'LineWidth',1,'Color',[0 0 0]);

% Create ylabel
ylabel({'Muscle activation (% MVIC)'});

% Create xlabel
xlabel({'Time (s)'});

% Create title
title({'sEMG - Normalized against MVIC'});

box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'XTickLabel',{'0','25','50','75','100','125'});

exportgraphics(f,'EMG-Process.png','Resolution',300)
end
